### ISSUE TITLE
Doesn't work with latest Lua firmware

### ISSUE THREAD

**Issue by Czayen** [ok1cdj/ESP8266-LUA#3]
Doesn't work with latest Lua firmware (version 0.9.5)
I can see the following in the terminal but no data gets sent to thingspeak. (I have WiFi connection and correct API key)

Sending data to thingspeak.com
Closing connection
Got disconnection...
Last temp: 213750
Temp:21.3750 C

**Comment by ok1cdj** [comment]
Hi, i'm still using nodemcu_512k_20141219.bin, the newest versions are buggy.

Ondra

**Comment by Czayen** [comment]
Thanks Ondrej, it works with that version.
